project:
  type: book
  output-dir: docs

lang: pt-BR

book:
  title: "EAE1106 - Métodos Computacionais para Economia"
  author: "[Danilo Souza](https://www.danilosouza.com/)"
  reader-mode: true

  page-footer:
    left: "© 2026 [Danilo Souza](https://www.danilosouza.com/) · Departamento de Economia · FEA-USP"
    right: "Material da disciplina **EAE1106 — Métodos Computacionais para Economia** · Feito com [Quarto](https://quarto.org/)"
  
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: alfabetizacao.qmd
      chapters:
        - fundamentos.qmd
        - primeiros_passos.qmd
        - inteligencia_artificial.qmd
        - objetos.qmd
        - iteracao.qmd
        - funcoes.qmd
        
    - part: pacotes.qmd
      chapters:
        - numpy.qmd
        - pandas.qmd
        - visualizacao.qmd
        - projeto_empirico.qmd
        
    - part: complemento.qmd
      chapters:
        - oop.qmd
        - intror.qmd
      
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    number-sections: true
    toc: true
    toc-location: right
    toc-depth: 3
    code-fold: false
    css: styles.css
    highlight-style: pygments

    author-meta: "Danilo Souza"
    
  pdf:
    documentclass: scrreprt



