project:
  type: book
  output-dir: docs

lang: pt-BR

book:
  title: "Métodos Computacionais para Economia"
  subtitle: "Faculdade de Economia, Administração, Contabilidade e Atuaria<br>Universidade de São Paulo"
  author: "[Danilo Souza](https://www.danilosouza.com/)"
  date: "2026-01-20"
  date-format: "DD [ de ] MMMM, YYYY"
  reader-mode: true

  repo-url: https://github.com/danilosouza-usp/eae1106
  repo-actions: [edit,issue]

  sidebar:
    search: false
    logo: images/usp-logo.jpg

  page-footer:
    left: "© 2026 [Danilo Souza](https://www.danilosouza.com/) · Departamento de Economia · FEA-USP"
    right: "Material da disciplina **EAE1106 — Métodos Computacionais para Economia** · Feito com [Quarto](https://quarto.org/)"
  
  chapters:
    - index.qmd
    - prefacio.qmd
    
    - part: alfabetizacao.qmd
      chapters:
        - fundamentos.qmd
        - primeiros_passos.qmd
        - inteligencia_artificial.qmd
        - objetos.qmd
        - iteracao.qmd
        - funcoes.qmd
        
    - part: pacotes.qmd
      chapters:
        - numpy.qmd
        - pandas.qmd
        - visualizacao.qmd
        - projeto_empirico.qmd
        
    - part: complemento.qmd
      chapters:
        - oop.qmd
        - intror.qmd
      
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    number-sections: true
    toc: true
    toc-location: right
    toc-depth: 3
    code-fold: false
    css: styles.css
    highlight-style: pygments
    link-external-newwindow: true
    author-meta: "Danilo Souza"
    
  pdf:
    documentclass: scrreprt



