project:
  type: book
  output-dir: docs

lang: pt-BR

book:
  title: "EAE1106 - Métodos Computacionais para Economia"
  author: "Danilo Souza"
  reader-mode: true

  page-footer:
    left: ""
    right: "Esse livro foi feito com <a href="https://quarto.org/">Quarto</a>".
  
  chapters:
    - index.qmd
    
    - part: "Alfabetização computacional e lógica básica"
      chapters:
        - fundamentos.qmd
        
    - part: "Computação numérica, análise de dados e visualização"
      chapters:
        - numpy.qmd
        
    - part: "Temas complementares"
      chapters:
        - oop.qmd
        - intror.qmd
      
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    toc-location: right
    toc-depth: 3

    author-meta: "Danilo Souza"
    
  pdf:
    documentclass: scrreprt



